import React, { useState, useEffect, useRef } from "react"
import axios from "axios"
import { motion, AnimatePresence } from "framer-motion"
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, ArcElement } from "chart.js"
import { Line, Doughnut } from "react-chartjs-2"
import { toast } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import {
  ChatBubbleLeftRightIcon,
  PaperAirplaneIcon,
  ArrowPathIcon,
  ChartBarIcon,
  CurrencyDollarIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  XCircleIcon,
  UserIcon,
  ClockIcon,
  CalendarIcon,
  BanknotesIcon,
  CreditCardIcon,
  WalletIcon,
  BuildingOfficeIcon,
  HomeIcon,
  ShoppingBagIcon,
  TruckIcon,
  GiftIcon,
  HeartIcon,
  AcademicCapIcon,
  BriefcaseIcon,
  WrenchScrewdriverIcon,
  PhoneIcon,
  ComputerDesktopIcon,
  FilmIcon,
  MusicalNoteIcon,
  BookOpenIcon,
  TicketIcon,
  PlaneIcon,
  CarIcon,
  TrainIcon,
  BusIcon,
  ShipIcon,
  BeakerIcon,
  HeartIcon as HeartIconSolid,
  StarIcon,
  SparklesIcon,
  FireIcon,
  BoltIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  CloudRainIcon,
  CloudSnowIcon,
  CloudLightningIcon,
  CloudFogIcon,
  CloudSunIcon,
  CloudMoonIcon,
  CloudRainSunIcon,
  CloudRainMoonIcon,
  CloudSnowSunIcon,
  CloudSnowMoonIcon,
  CloudLightningSunIcon,
  CloudLightningMoonIcon,
  CloudFogSunIcon,
  CloudFogMoonIcon,
  SunIcon as SunIconSolid,
  MoonIcon as MoonIconSolid,
  StarIcon as StarIconSolid,
  HeartIcon as HeartIconSolid2,
  SparklesIcon as SparklesIconSolid,
  FireIcon as FireIconSolid,
  BoltIcon as BoltIconSolid,
  SunIcon as SunIconSolid2,
  MoonIcon as MoonIconSolid2,
  CloudIcon as CloudIconSolid,
  CloudRainIcon as CloudRainIconSolid,
  CloudSnowIcon as CloudSnowIconSolid,
  CloudLightningIcon as CloudLightningIconSolid,
  CloudFogIcon as CloudFogIconSolid,
  CloudSunIcon as CloudSunIconSolid,
  CloudMoonIcon as CloudMoonIconSolid,
  CloudRainSunIcon as CloudRainSunIconSolid,
  CloudRainMoonIcon as CloudRainMoonIconSolid,
  CloudSnowSunIcon as CloudSnowSunIconSolid,
  CloudSnowMoonIcon as CloudSnowMoonIconSolid,
  CloudLightningSunIcon as CloudLightningSunIconSolid,
  CloudLightningMoonIcon as CloudLightningMoonIconSolid,
  CloudFogSunIcon as CloudFogSunIconSolid,
  CloudFogMoonIcon as CloudFogMoonIconSolid,
} from "@heroicons/react/24/outline"

// Đăng ký các components cần thiết cho Chart.js
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  ArcElement
)

// ... rest of the code remains unchanged ... 